
services:
  db:
    image: postgres:15
    container_name: todo_postgres
    environment:
      - POSTGRES_USER=ialloni
      - POSTGRES_PASSWORD=qwertyqwerty
      - POSTGRES_DB=todo_postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: todo_redis
    ports:
      - "6379:6379"
volumes:
  pgdata: